/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'home_shield';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String ACCOUNT_ICON = 'assets/icons/account_icon.png';
  static const String CLOSE_ICON = 'assets/icons/close_icon.png';
  static const String EMAIL_ICON = 'assets/icons/email_icon.png';
  static const String FACEBOOK_ICON = 'assets/icons/facebook_icon.png';
  static const String GOOGLE_ICON = 'assets/icons/google_icon.png';
  static const String HAND_OFF_ICON = 'assets/icons/hand_off_icon.png';
  static const String LOCATION_ICON = 'assets/icons/location_icon.PNG';
  static const String LOCK_ICON = 'assets/icons/lock_icon.png';
  static const String PENCIL_ICON = 'assets/icons/pencil_icon.png';
  static const String PHONE_ICON = 'assets/icons/phone_icon.png';
  static const String REDIRECT_MY_LOCATION_ICON = 'assets/icons/redirect_my_location_icon.png';
  static const String AVATAR_SAMPLE = 'assets/images/avatar_sample.jpg';
  static const String FRIEND = 'assets/images/friend.png';
  static const String LOGO = 'assets/images/logo.png';
  static const String UPLOAD_SAMPLE = 'assets/images/upload_sample.png';
}
